# Generated by Django 5.1.1 on 2024-10-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_delete_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSavedCity',
        ),
    ]
