# Generated by Django 5.1.1 on 2024-09-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0004_customuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uid',
        ),
    ]
