# Generated by Django 5.1.1 on 2024-09-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0006_usersavedcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
