# Generated by Django 5.1.1 on 2024-09-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0007_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
